site_name: OBO Relation Ontology
theme: readthedocs
nav:
  - Basics:
      - Index: index.md
      - Quickstart: quickstart.md
      - History: history.md
  - Guide:
      - Introduction: introduction.md
      - OWL Concepts: owl.md
      - Annotation Properties: annotation-properties.md
      - Object Properties: object-properties.md
      - Property Chains: property-chains.md
      - Identifiers: identifiers.md
      - Shortcut Relations: shortcut-relations.md
      - Examples: examples.md
      - Domain and Ranges: domain-or-range-specific-relation.md
  - Design Patterns:
    - Design Patterns Overview: design-patterns.md
    - Reflexivity: reflexivity.md
    - Direct and Indirect Relations: direct-and-indirect-relations.md
    - Interaction Relations: interaction-relations.md
  - Modules:
    - Modules Overview: modules.md
    - RO Core: ro-core.md
    - RO Neuron: ro-neuro.md
    - Causal Relations: causal-relations.md
  - Links to other resources:
    - mappings: mappings.md
  - Semantics:
    - RO and BFO: ro-and-bfo.md
    - Temporal Semantics: temporal-semantics.md
  - Legacy:
    - Changes since 2005 paper: changes-since-2005-paper.md
    - Chado Databases: ro-and-chado.md
    - RO and OBO Format: ro-and-obo-format.md
  - Contributing:
    - Editors guide: editing-ro.md
