PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX term_tracker_item: <http://purl.obolibrary.org/obo/IAO_0000233>

SELECT ?term ?term_tracker ?term_tracker_type WHERE {
  ?term term_tracker_item: ?term_tracker .
  FILTER(DATATYPE(?term_tracker) != xsd:anyURI)
  BIND(DATATYPE(?term_tracker) as ?term_tracker_type) 
}

