prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?property ?def (group_concat(?superProperty) as ?superPropertyList) WHERE 
{
  ?property a owl:ObjectProperty .
  OPTIONAL { ?property rdfs:subPropertyOf ?superProperty } .
  OPTIONAL { ?property def: ?def } 
}
GROUP BY ?property ?def
